# Generated by Django 4.0 on 2022-01-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='todoapp.taskstatus'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='types', to='todoapp.tasktype'),
        ),
    ]
