# Generated by Django 4.0 on 2022-01-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todotask_status_alter_todotask_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='type',
        ),
        migrations.AddField(
            model_name='todotask',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', through='todoapp.TodoType', to='todoapp.TaskType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='todoapp.taskstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='todotype',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='todos', to='todoapp.todotask', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='todotype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='typess', to='todoapp.tasktype', verbose_name='Типы'),
        ),
    ]
