# Generated by Django 4.0 on 2022-01-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20220125_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='types_new',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='types_old',
        ),
    ]
