# Generated by Django 4.0 on 2022-01-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_types_new_todotask_types_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoType',
        ),
    ]
