# Generated by Django 4.0 on 2022-01-28 10:18

from django.db import migrations, models
import todoapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_delete_todotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[todoapp.validators.WordLengthValidator(50)], verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(max_length=25, validators=[todoapp.validators.MinLengthValidator(3)], verbose_name='Название задачи'),
        ),
    ]
