# Generated by Django 4.0 on 2022-02-07 04:49

from django.db import migrations, models
import todoapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_todotask_description_alter_todotask_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[todoapp.validators.MinLengthValidator(3)], verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=500, null=True, validators=[todoapp.validators.WordLengthValidator(50)], verbose_name='Описание проекта')),
                ('begin_at', models.DateTimeField(verbose_name='Время начала')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
        ),
    ]
