# Generated by Django 4.0 on 2022-02-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_todoproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoproject',
            name='begin_at',
            field=models.DateField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
