# Generated by Django 4.0 on 2022-02-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_todoproject_begin_at_alter_todoproject_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='project', to='todoapp.todoproject', verbose_name='Проект'),
        ),
    ]
