# Generated by Django 4.0 on 2022-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_todotask_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
