# Generated by Django 4.0 on 2022-02-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_taskstatus_is_deleted_tasktype_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='todoapp.todoproject', verbose_name='Проект'),
        ),
    ]
