# Generated by Django 4.0 on 2022-02-23 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0013_alter_todotask_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoproject',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Участник проекта'),
        ),
    ]
