# Generated by Django 4.0 on 2022-02-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_todoproject_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoproject',
            options={'permissions': [('can_edit_users', 'Можно менять участников проекта')]},
        ),
    ]
