# Generated by Django 4.0 on 2022-03-01 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0015_alter_todoproject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoproject',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Участник проекта'),
        ),
    ]
